---


# 自签证书及配置文件目录
tmp_files: ./tmp_files

# master ip,根据实际情况调整
master_ip: 192.168.165.81

# cluster ip,根据实际情况调整
cluster_ip: 10.0.0.0

# cluster cidr
cluster_cidr: 10.244.0.0

# cluster dns
cluster_dns: 10.0.0.10

# token ID, 可以自行生成
bootstrap_token_id: c8ad9c
bootstrap_token: 2e4d610cf3e7426e 


# 自签etcd证书时hostname参数值
# etcd在master节点上(hostname => k8s-master-01)
# 根据实际情况调整
etcd_host:
  - 127.0.0.1
  - k8s-master-01
  - 192.168.165.81

# 自签kube-apiserver证书时hostname参数值
# 根据实际情况调整
apiserver_host:
  - 10.0.0.1
  - 127.0.0.1
  - kubernetes
  - kubernetes.default
  - kubernetes.default.svc
  - kubernetes.default.svc.cluster
  - kubernetes.default.svc.cluster.local
  - x.oiox.cn
  - k.oiox.cn
  - l.oiox.cn
  - o.oiox.cn
  - 192.168.165.81
  - k8s-master-01
