---

- name: 1.系统环境初始化
  gather_facts: false
  become: false
  hosts: 
    - worker
  roles:
    - comm
  tags: worker

- name: 部署docker&containerd服务
  gather_facts: false
  become: true
  hosts:
    - worker
  roles:
    - containerd
  tags: containerd

- name: 部署k8s-worker节点
  gather_facts: false
  become: true
  hosts:
    - worker
  roles:
    - worker
  tags: worker