---

- name: 1.系统环境初始化
  gather_facts: false
  become: true
  hosts:
    - k8s
  roles:
    - comm
  tags: comm

- name: 2.自签认证证书
  gather_facts: false
  become: false
  hosts: 
    - localhost
  roles:
    - cert
  tags: cert

- name: 3.部署docker&containerd服务
  gather_facts: false
  become: true
  hosts:
    - k8s
  roles:
    - containerd
  tags: containerd

- name: 4.部署etcd集群
  gather_facts: false
  become: true
  hosts:
    - etcd
  roles:
    - etcd
  tags: etcd

- name: 5.部署k8s-master节点
  gather_facts: false
  become: true
  hosts:
    - master
  roles:
    - master
  tags: master
