---

- name: 创建自签证书及配置文件目录
  file:
    path: "{{tmp_files}}"
    state: directory
    recurse: yes

- name: 准备boostrap.secret.yaml文件
  template:
    src: bootstrap.secret.yaml.j2
    dest: "{{tmp_files}}/bootstrap.secret.yaml"

- name: 准备自签证书文件
  copy: 
    src: "{{item}}"
    dest: "{{tmp_files}}/{{item}}"
  with_items:
    - admin-csr.json
    - apiserver-csr.json
    - ca-config.json
    - ca-csr.json
    - controller-manager-csr.json
    - etcd-ca-csr.json
    - etcd-csr.json
    - front-proxy-ca-csr.json
    - front-proxy-client-csr.json
    - kube-proxy-csr.json
    - scheduler-csr.json

- name: 准备自签证书脚本
  template: 
    src: gen_cert.bash.j2 
    dest: "{{tmp_files}}/gen_cert.bash" 

- name: 生成自签证书文件
  shell: |
    cd "{{tmp_files}}"
    /usr/bin/bash gen_cert.bash

- name: 准备配置文件脚本
  template:
    src: gen_kubeconfig.bash.j2
    dest: "{{tmp_files}}/gen_kubeconfig.bash"

- name: 生成配置文件
  shell: |
    cd "{{tmp_files}}"
    /usr/bin/bash gen_kubeconfig.bash
