---

# - name: 安装docker和containerd-io
#   shell: |
#     apt install -y docker-ce docker-ce-cli containerd.io

- name: 安装docker和containerd
  apt:
    name: "{{ item }}"
    state: present
  with_items:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: 添加containerd配置文件
  copy:
    src: config.toml
    dest: /etc/containerd/config.toml

- name: 启动docker服务
  systemd:
    name: docker
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: 启动containerd服务
  systemd:
    name: containerd
    state: restarted
    enabled: yes
    daemon_reload: yes
  