---

- name: 上传etcd服务证书
  copy:
    src: "{{item}}"
    dest: /usr/local/etcd/cert
  with_items:
    - etcd.pem
    - etcd-key.pem
    - etcd-ca.pem
    - etcd-ca-key.pem

- name: 上传etcd服务service配置
  copy:
    src: etcd.service
    dest: /lib/systemd/system/etcd.service

- name: 上传etcd.config.yaml文件
  template:
    src: etcd.config.yaml.j2
    dest: /usr/local/etcd/config/etcd.config.yaml

- name: 上传etcd服务二进制文件
  copy:
    src: "{{item}}"
    dest: /usr/local/bin/
  with_items:
    - etcd
    - etcdctl
    - etcdutl

- name: 启动etcd服务组件
  systemd:
    name: etcd
    enabled: yes
    state: restarted
    daemon_reload: yes