---

- name: 上传containerd服务二进制文件
  copy:
    src: "{{item}}"
    dest: /usr/local/bin
  with_items:
    - containerd
    - containerd-shim   
    - containerd-shim-runc-v1  
    - containerd-shim-runc-v2  
    - containerd-stress
    - ctr
    - crictl

- name: 上传containerd服务配置文件
  copy:
    src: containerd.service
    dest: /lib/systemd/system

- name: 上传containerd配置文件
  copy:
    src: config.toml
    dest: /etc/containerd/

- name: 上传containerd代理配置
  copy:
    src: hosts.toml
    dest: /etc/containerd/certs.d/docker.io/

- name: 启动containerd服务组件
  systemd:
    name: containerd
    enabled: yes
    state: restarted
    daemon_reload: yes
  